print("Beep has been recently updated with a square root function")
print("Beep wants you to put his new update to the test")
print("Please enter a whole number")
number = int(input())
square_root = float(number ** 0.5)
print("")
print(f"Square root of {number} is {square_root}")
print("")
print("Beep wants to know what is your name")
name = input()
print(f"Beep is very grateful for your help {name}")
print("Beep asks you to write down a 3-5 line review of his new software update")
print("Please begin to write line 1")
line_1 = input()
print("Please begin to write line 2")
line_2 = input()
print("Please begin to write line 3")
line_3 = input()
print("Thank you for your review")
print("Beep will now send this review back to his developers")
print("This is how the review looks:")
print("")
print("|---------------------------------------------------------------------|")
print("|                            Review letter                            |")
print("|---------------------------------------------------------------------|")
print(f"|\tBeep has helped me find out the square root of {number}")
print(f"|\tHe instantly gave me the answer, {square_root}, I am very impressed")
print(f"|\t{line_1}")
print(f"|\t{line_2}")
print(f"|\t{line_3}")
print("|---------------------------------------------------------------------|")
print(f"| Best Regards, {name}")
print("|---------------------------------------------------------------------|")