print("Please enter number of lives")
beep_lives = int(input())
print("")
print("Please enter energy level")
beep_energy = int(input())
print("")
print("Please enter shield level")
beep_shield = int(input())
print("")
print("Health has been set.")
print("")
print(f"Lives:  {'♥' * beep_lives}")
print(f"Energy: {'♦' * beep_energy}")
print(f"Shield: {'♦' * beep_shield}")