print("Please enter a character for the eye")
eye = input()

print("Beep's expression is now as follows:")
print("")
print("   __,_,")
print("  [_|_/")
print("   //")
print(" _//    __")
print(f"(_|)   |{eye}{eye}|")
print(" \ \__ \--/ __")
print("  \o__|----|  |   __")
print("      \ }{ /\ )_ / _\ ")
print("      /\__/\ \__O (__")
print("     (--/\--)    \__/")
print("     _)(  )(_")
print("    `---''---`")